// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/example.proto

package com.mattie.pb;

public final class HotelListSearchProtos {
  private HotelListSearchProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FilterItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mattie.pb.FilterItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 filterId = 1;</code>
     */
    boolean hasFilterId();
    /**
     * <code>optional int32 filterId = 1;</code>
     */
    int getFilterId();

    /**
     * <code>optional string title = 2;</code>
     */
    boolean hasTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 2;</code>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string value = 3;</code>
     */
    boolean hasValue();
    /**
     * <code>optional string value = 3;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 3;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code com.mattie.pb.FilterItem}
   */
  public  static final class FilterItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mattie.pb.FilterItem)
      FilterItemOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FilterItem.newBuilder() to construct.
    private FilterItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FilterItem() {
      filterId_ = 0;
      title_ = "";
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FilterItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              filterId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              title_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              value_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_FilterItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_FilterItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mattie.pb.HotelListSearchProtos.FilterItem.class, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder.class);
    }

    private int bitField0_;
    public static final int FILTERID_FIELD_NUMBER = 1;
    private int filterId_;
    /**
     * <code>optional int32 filterId = 1;</code>
     */
    public boolean hasFilterId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 filterId = 1;</code>
     */
    public int getFilterId() {
      return filterId_;
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile java.lang.Object title_;
    /**
     * <code>optional string title = 2;</code>
     */
    public boolean hasTitle() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VALUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 3;</code>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string value = 3;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          value_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string value = 3;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, filterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, value_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, filterId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mattie.pb.HotelListSearchProtos.FilterItem)) {
        return super.equals(obj);
      }
      com.mattie.pb.HotelListSearchProtos.FilterItem other = (com.mattie.pb.HotelListSearchProtos.FilterItem) obj;

      boolean result = true;
      result = result && (hasFilterId() == other.hasFilterId());
      if (hasFilterId()) {
        result = result && (getFilterId()
            == other.getFilterId());
      }
      result = result && (hasTitle() == other.hasTitle());
      if (hasTitle()) {
        result = result && getTitle()
            .equals(other.getTitle());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilterId()) {
        hash = (37 * hash) + FILTERID_FIELD_NUMBER;
        hash = (53 * hash) + getFilterId();
      }
      if (hasTitle()) {
        hash = (37 * hash) + TITLE_FIELD_NUMBER;
        hash = (53 * hash) + getTitle().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.FilterItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mattie.pb.HotelListSearchProtos.FilterItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mattie.pb.FilterItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mattie.pb.FilterItem)
        com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_FilterItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_FilterItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mattie.pb.HotelListSearchProtos.FilterItem.class, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder.class);
      }

      // Construct using com.mattie.pb.HotelListSearchProtos.FilterItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        filterId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        title_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_FilterItem_descriptor;
      }

      public com.mattie.pb.HotelListSearchProtos.FilterItem getDefaultInstanceForType() {
        return com.mattie.pb.HotelListSearchProtos.FilterItem.getDefaultInstance();
      }

      public com.mattie.pb.HotelListSearchProtos.FilterItem build() {
        com.mattie.pb.HotelListSearchProtos.FilterItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mattie.pb.HotelListSearchProtos.FilterItem buildPartial() {
        com.mattie.pb.HotelListSearchProtos.FilterItem result = new com.mattie.pb.HotelListSearchProtos.FilterItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.filterId_ = filterId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.title_ = title_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mattie.pb.HotelListSearchProtos.FilterItem) {
          return mergeFrom((com.mattie.pb.HotelListSearchProtos.FilterItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mattie.pb.HotelListSearchProtos.FilterItem other) {
        if (other == com.mattie.pb.HotelListSearchProtos.FilterItem.getDefaultInstance()) return this;
        if (other.hasFilterId()) {
          setFilterId(other.getFilterId());
        }
        if (other.hasTitle()) {
          bitField0_ |= 0x00000002;
          title_ = other.title_;
          onChanged();
        }
        if (other.hasValue()) {
          bitField0_ |= 0x00000004;
          value_ = other.value_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mattie.pb.HotelListSearchProtos.FilterItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mattie.pb.HotelListSearchProtos.FilterItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int filterId_ ;
      /**
       * <code>optional int32 filterId = 1;</code>
       */
      public boolean hasFilterId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 filterId = 1;</code>
       */
      public int getFilterId() {
        return filterId_;
      }
      /**
       * <code>optional int32 filterId = 1;</code>
       */
      public Builder setFilterId(int value) {
        bitField0_ |= 0x00000001;
        filterId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 filterId = 1;</code>
       */
      public Builder clearFilterId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        filterId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 2;</code>
       */
      public boolean hasTitle() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder clearTitle() {
        bitField0_ = (bitField0_ & ~0x00000002);
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 2;</code>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 3;</code>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            value_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000004);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 3;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mattie.pb.FilterItem)
    }

    // @@protoc_insertion_point(class_scope:com.mattie.pb.FilterItem)
    private static final com.mattie.pb.HotelListSearchProtos.FilterItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mattie.pb.HotelListSearchProtos.FilterItem();
    }

    public static com.mattie.pb.HotelListSearchProtos.FilterItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FilterItem>
        PARSER = new com.google.protobuf.AbstractParser<FilterItem>() {
      public FilterItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FilterItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FilterItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterItem> getParserForType() {
      return PARSER;
    }

    public com.mattie.pb.HotelListSearchProtos.FilterItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HotelListSearchRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mattie.pb.HotelListSearchRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 cityId = 1;</code>
     */
    boolean hasCityId();
    /**
     * <code>optional int32 cityId = 1;</code>
     */
    int getCityId();

    /**
     * <code>optional int32 hotelDateType = 2;</code>
     */
    boolean hasHotelDateType();
    /**
     * <code>optional int32 hotelDateType = 2;</code>
     */
    int getHotelDateType();

    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem> 
        getFiltersList();
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    com.mattie.pb.HotelListSearchProtos.FilterItem getFilters(int index);
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    int getFiltersCount();
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    java.util.List<? extends com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder> 
        getFiltersOrBuilderList();
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder getFiltersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.mattie.pb.HotelListSearchRequest}
   */
  public  static final class HotelListSearchRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mattie.pb.HotelListSearchRequest)
      HotelListSearchRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HotelListSearchRequest.newBuilder() to construct.
    private HotelListSearchRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HotelListSearchRequest() {
      cityId_ = 0;
      hotelDateType_ = 0;
      filters_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HotelListSearchRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              cityId_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              hotelDateType_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                filters_ = new java.util.ArrayList<com.mattie.pb.HotelListSearchProtos.FilterItem>();
                mutable_bitField0_ |= 0x00000004;
              }
              filters_.add(
                  input.readMessage(com.mattie.pb.HotelListSearchProtos.FilterItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          filters_ = java.util.Collections.unmodifiableList(filters_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.class, com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.Builder.class);
    }

    private int bitField0_;
    public static final int CITYID_FIELD_NUMBER = 1;
    private int cityId_;
    /**
     * <code>optional int32 cityId = 1;</code>
     */
    public boolean hasCityId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 cityId = 1;</code>
     */
    public int getCityId() {
      return cityId_;
    }

    public static final int HOTELDATETYPE_FIELD_NUMBER = 2;
    private int hotelDateType_;
    /**
     * <code>optional int32 hotelDateType = 2;</code>
     */
    public boolean hasHotelDateType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 hotelDateType = 2;</code>
     */
    public int getHotelDateType() {
      return hotelDateType_;
    }

    public static final int FILTERS_FIELD_NUMBER = 3;
    private java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem> filters_;
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    public java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem> getFiltersList() {
      return filters_;
    }
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    public java.util.List<? extends com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder> 
        getFiltersOrBuilderList() {
      return filters_;
    }
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    public int getFiltersCount() {
      return filters_.size();
    }
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    public com.mattie.pb.HotelListSearchProtos.FilterItem getFilters(int index) {
      return filters_.get(index);
    }
    /**
     * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
     */
    public com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder getFiltersOrBuilder(
        int index) {
      return filters_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, cityId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, hotelDateType_);
      }
      for (int i = 0; i < filters_.size(); i++) {
        output.writeMessage(3, filters_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, cityId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, hotelDateType_);
      }
      for (int i = 0; i < filters_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, filters_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest)) {
        return super.equals(obj);
      }
      com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest other = (com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest) obj;

      boolean result = true;
      result = result && (hasCityId() == other.hasCityId());
      if (hasCityId()) {
        result = result && (getCityId()
            == other.getCityId());
      }
      result = result && (hasHotelDateType() == other.hasHotelDateType());
      if (hasHotelDateType()) {
        result = result && (getHotelDateType()
            == other.getHotelDateType());
      }
      result = result && getFiltersList()
          .equals(other.getFiltersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasCityId()) {
        hash = (37 * hash) + CITYID_FIELD_NUMBER;
        hash = (53 * hash) + getCityId();
      }
      if (hasHotelDateType()) {
        hash = (37 * hash) + HOTELDATETYPE_FIELD_NUMBER;
        hash = (53 * hash) + getHotelDateType();
      }
      if (getFiltersCount() > 0) {
        hash = (37 * hash) + FILTERS_FIELD_NUMBER;
        hash = (53 * hash) + getFiltersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mattie.pb.HotelListSearchRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mattie.pb.HotelListSearchRequest)
        com.mattie.pb.HotelListSearchProtos.HotelListSearchRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.class, com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.Builder.class);
      }

      // Construct using com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFiltersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        cityId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        hotelDateType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchRequest_descriptor;
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest getDefaultInstanceForType() {
        return com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.getDefaultInstance();
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest build() {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest buildPartial() {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest result = new com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.cityId_ = cityId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.hotelDateType_ = hotelDateType_;
        if (filtersBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            filters_ = java.util.Collections.unmodifiableList(filters_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.filters_ = filters_;
        } else {
          result.filters_ = filtersBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest) {
          return mergeFrom((com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest other) {
        if (other == com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest.getDefaultInstance()) return this;
        if (other.hasCityId()) {
          setCityId(other.getCityId());
        }
        if (other.hasHotelDateType()) {
          setHotelDateType(other.getHotelDateType());
        }
        if (filtersBuilder_ == null) {
          if (!other.filters_.isEmpty()) {
            if (filters_.isEmpty()) {
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureFiltersIsMutable();
              filters_.addAll(other.filters_);
            }
            onChanged();
          }
        } else {
          if (!other.filters_.isEmpty()) {
            if (filtersBuilder_.isEmpty()) {
              filtersBuilder_.dispose();
              filtersBuilder_ = null;
              filters_ = other.filters_;
              bitField0_ = (bitField0_ & ~0x00000004);
              filtersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFiltersFieldBuilder() : null;
            } else {
              filtersBuilder_.addAllMessages(other.filters_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int cityId_ ;
      /**
       * <code>optional int32 cityId = 1;</code>
       */
      public boolean hasCityId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 cityId = 1;</code>
       */
      public int getCityId() {
        return cityId_;
      }
      /**
       * <code>optional int32 cityId = 1;</code>
       */
      public Builder setCityId(int value) {
        bitField0_ |= 0x00000001;
        cityId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 cityId = 1;</code>
       */
      public Builder clearCityId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        cityId_ = 0;
        onChanged();
        return this;
      }

      private int hotelDateType_ ;
      /**
       * <code>optional int32 hotelDateType = 2;</code>
       */
      public boolean hasHotelDateType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 hotelDateType = 2;</code>
       */
      public int getHotelDateType() {
        return hotelDateType_;
      }
      /**
       * <code>optional int32 hotelDateType = 2;</code>
       */
      public Builder setHotelDateType(int value) {
        bitField0_ |= 0x00000002;
        hotelDateType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 hotelDateType = 2;</code>
       */
      public Builder clearHotelDateType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        hotelDateType_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem> filters_ =
        java.util.Collections.emptyList();
      private void ensureFiltersIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          filters_ = new java.util.ArrayList<com.mattie.pb.HotelListSearchProtos.FilterItem>(filters_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mattie.pb.HotelListSearchProtos.FilterItem, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder, com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder> filtersBuilder_;

      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem> getFiltersList() {
        if (filtersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(filters_);
        } else {
          return filtersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public int getFiltersCount() {
        if (filtersBuilder_ == null) {
          return filters_.size();
        } else {
          return filtersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public com.mattie.pb.HotelListSearchProtos.FilterItem getFilters(int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);
        } else {
          return filtersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder setFilters(
          int index, com.mattie.pb.HotelListSearchProtos.FilterItem value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.set(index, value);
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder setFilters(
          int index, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.set(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder addFilters(com.mattie.pb.HotelListSearchProtos.FilterItem value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder addFilters(
          int index, com.mattie.pb.HotelListSearchProtos.FilterItem value) {
        if (filtersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFiltersIsMutable();
          filters_.add(index, value);
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder addFilters(
          com.mattie.pb.HotelListSearchProtos.FilterItem.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder addFilters(
          int index, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder builderForValue) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.add(index, builderForValue.build());
          onChanged();
        } else {
          filtersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder addAllFilters(
          java.lang.Iterable<? extends com.mattie.pb.HotelListSearchProtos.FilterItem> values) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, filters_);
          onChanged();
        } else {
          filtersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder clearFilters() {
        if (filtersBuilder_ == null) {
          filters_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          filtersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public Builder removeFilters(int index) {
        if (filtersBuilder_ == null) {
          ensureFiltersIsMutable();
          filters_.remove(index);
          onChanged();
        } else {
          filtersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public com.mattie.pb.HotelListSearchProtos.FilterItem.Builder getFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder getFiltersOrBuilder(
          int index) {
        if (filtersBuilder_ == null) {
          return filters_.get(index);  } else {
          return filtersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public java.util.List<? extends com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder> 
           getFiltersOrBuilderList() {
        if (filtersBuilder_ != null) {
          return filtersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(filters_);
        }
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public com.mattie.pb.HotelListSearchProtos.FilterItem.Builder addFiltersBuilder() {
        return getFiltersFieldBuilder().addBuilder(
            com.mattie.pb.HotelListSearchProtos.FilterItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public com.mattie.pb.HotelListSearchProtos.FilterItem.Builder addFiltersBuilder(
          int index) {
        return getFiltersFieldBuilder().addBuilder(
            index, com.mattie.pb.HotelListSearchProtos.FilterItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.mattie.pb.FilterItem filters = 3;</code>
       */
      public java.util.List<com.mattie.pb.HotelListSearchProtos.FilterItem.Builder> 
           getFiltersBuilderList() {
        return getFiltersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mattie.pb.HotelListSearchProtos.FilterItem, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder, com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder> 
          getFiltersFieldBuilder() {
        if (filtersBuilder_ == null) {
          filtersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mattie.pb.HotelListSearchProtos.FilterItem, com.mattie.pb.HotelListSearchProtos.FilterItem.Builder, com.mattie.pb.HotelListSearchProtos.FilterItemOrBuilder>(
                  filters_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          filters_ = null;
        }
        return filtersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mattie.pb.HotelListSearchRequest)
    }

    // @@protoc_insertion_point(class_scope:com.mattie.pb.HotelListSearchRequest)
    private static final com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest();
    }

    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HotelListSearchRequest>
        PARSER = new com.google.protobuf.AbstractParser<HotelListSearchRequest>() {
      public HotelListSearchRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HotelListSearchRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HotelListSearchRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HotelListSearchRequest> getParserForType() {
      return PARSER;
    }

    public com.mattie.pb.HotelListSearchProtos.HotelListSearchRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HotelListSearchResonseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mattie.pb.HotelListSearchResonse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    boolean hasResultCode();
    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    int getResultCode();

    /**
     * <code>optional string resultMessage = 2;</code>
     */
    boolean hasResultMessage();
    /**
     * <code>optional string resultMessage = 2;</code>
     */
    java.lang.String getResultMessage();
    /**
     * <code>optional string resultMessage = 2;</code>
     */
    com.google.protobuf.ByteString
        getResultMessageBytes();
  }
  /**
   * Protobuf type {@code com.mattie.pb.HotelListSearchResonse}
   */
  public  static final class HotelListSearchResonse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.mattie.pb.HotelListSearchResonse)
      HotelListSearchResonseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HotelListSearchResonse.newBuilder() to construct.
    private HotelListSearchResonse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HotelListSearchResonse() {
      resultCode_ = 0;
      resultMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HotelListSearchResonse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              resultCode_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              resultMessage_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchResonse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchResonse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.class, com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.Builder.class);
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    public boolean hasResultCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int RESULTMESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object resultMessage_;
    /**
     * <code>optional string resultMessage = 2;</code>
     */
    public boolean hasResultMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string resultMessage = 2;</code>
     */
    public java.lang.String getResultMessage() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          resultMessage_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string resultMessage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResultMessageBytes() {
      java.lang.Object ref = resultMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resultMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resultMessage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resultMessage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse)) {
        return super.equals(obj);
      }
      com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse other = (com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse) obj;

      boolean result = true;
      result = result && (hasResultCode() == other.hasResultCode());
      if (hasResultCode()) {
        result = result && (getResultCode()
            == other.getResultCode());
      }
      result = result && (hasResultMessage() == other.hasResultMessage());
      if (hasResultMessage()) {
        result = result && getResultMessage()
            .equals(other.getResultMessage());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResultCode()) {
        hash = (37 * hash) + RESULTCODE_FIELD_NUMBER;
        hash = (53 * hash) + getResultCode();
      }
      if (hasResultMessage()) {
        hash = (37 * hash) + RESULTMESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getResultMessage().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mattie.pb.HotelListSearchResonse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mattie.pb.HotelListSearchResonse)
        com.mattie.pb.HotelListSearchProtos.HotelListSearchResonseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchResonse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchResonse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.class, com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.Builder.class);
      }

      // Construct using com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resultCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        resultMessage_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mattie.pb.HotelListSearchProtos.internal_static_com_mattie_pb_HotelListSearchResonse_descriptor;
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse getDefaultInstanceForType() {
        return com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.getDefaultInstance();
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse build() {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse buildPartial() {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse result = new com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.resultCode_ = resultCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.resultMessage_ = resultMessage_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse) {
          return mergeFrom((com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse other) {
        if (other == com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse.getDefaultInstance()) return this;
        if (other.hasResultCode()) {
          setResultCode(other.getResultCode());
        }
        if (other.hasResultMessage()) {
          bitField0_ |= 0x00000002;
          resultMessage_ = other.resultMessage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resultCode_ ;
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public boolean hasResultCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder setResultCode(int value) {
        bitField0_ |= 0x00000001;
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resultMessage_ = "";
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public boolean hasResultMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public java.lang.String getResultMessage() {
        java.lang.Object ref = resultMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            resultMessage_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResultMessageBytes() {
        java.lang.Object ref = resultMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resultMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public Builder setResultMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public Builder clearResultMessage() {
        bitField0_ = (bitField0_ & ~0x00000002);
        resultMessage_ = getDefaultInstance().getResultMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string resultMessage = 2;</code>
       */
      public Builder setResultMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        resultMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.mattie.pb.HotelListSearchResonse)
    }

    // @@protoc_insertion_point(class_scope:com.mattie.pb.HotelListSearchResonse)
    private static final com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse();
    }

    public static com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<HotelListSearchResonse>
        PARSER = new com.google.protobuf.AbstractParser<HotelListSearchResonse>() {
      public HotelListSearchResonse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new HotelListSearchResonse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HotelListSearchResonse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HotelListSearchResonse> getParserForType() {
      return PARSER;
    }

    public com.mattie.pb.HotelListSearchProtos.HotelListSearchResonse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mattie_pb_FilterItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mattie_pb_FilterItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mattie_pb_HotelListSearchRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mattie_pb_HotelListSearchRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mattie_pb_HotelListSearchResonse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_mattie_pb_HotelListSearchResonse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026src/main/example.proto\022\rcom.mattie.pb\"" +
      "<\n\nFilterItem\022\020\n\010filterId\030\001 \001(\005\022\r\n\005title" +
      "\030\002 \001(\t\022\r\n\005value\030\003 \001(\t\"k\n\026HotelListSearch" +
      "Request\022\016\n\006cityId\030\001 \001(\005\022\025\n\rhotelDateType" +
      "\030\002 \001(\005\022*\n\007filters\030\003 \003(\0132\031.com.mattie.pb." +
      "FilterItem\"C\n\026HotelListSearchResonse\022\022\n\n" +
      "resultCode\030\001 \001(\005\022\025\n\rresultMessage\030\002 \001(\tB" +
      "(\n\rcom.mattie.pbB\025HotelListSearchProtosH" +
      "\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mattie_pb_FilterItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mattie_pb_FilterItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mattie_pb_FilterItem_descriptor,
        new java.lang.String[] { "FilterId", "Title", "Value", });
    internal_static_com_mattie_pb_HotelListSearchRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mattie_pb_HotelListSearchRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mattie_pb_HotelListSearchRequest_descriptor,
        new java.lang.String[] { "CityId", "HotelDateType", "Filters", });
    internal_static_com_mattie_pb_HotelListSearchResonse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mattie_pb_HotelListSearchResonse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_mattie_pb_HotelListSearchResonse_descriptor,
        new java.lang.String[] { "ResultCode", "ResultMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
